name: Build Jar

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build Java
      shell: cmd
      run: |
        call CompileMarsClass.bat

    - name: Package jar file
      shell: cmd
      run: |
        call CreateMarsJar.bat
        rename Mars.jar Mars_CO_${{  github.ref_name }}.jar

    - name: Zip example files
      shell: cmd
      run: |
        zip Mars_CO_${{  github.ref_name }}_example.zip adduo.class bhelbal.class subuo.class testcode.asm

    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Mars_CO_${{  github.ref_name }}.jar
          Mars_CO_${{  github.ref_name }}_example.zip
        draft: true
