name: Build Jar

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build Java
      shell: cmd
      run: |
        call CompileMarsClass.bat

    - name: Package jar file
      shell: cmd
      run: |
        call CreateMarsJar.bat
        rename Mars.jar Mars_CO_${{  github.ref_name }}.jar

    - name: Zip test file
      shell: cmd
      run: |
        cd test
        python -u zipTestClass.py MarsTest.zip
        move MarsTest.zip ..\Mars_Test_CO_${{  github.ref_name }}.zip
        cd ..

    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Mars_CO_${{  github.ref_name }}.jar
          Mars_Test_CO_${{  github.ref_name }}.zip
        draft: true

    - name: Test
      shell: cmd
      run: |
        move Mars_CO_${{  github.ref_name }}.jar test\mars.jar
        cd test
        java -jar mars.jar testcode.asm mc CompactLargeText coL1 cl bhelbal.class ig > testTemp.txt
        fc testTemp.txt stdout.txt
